Descriptive Statistics

In [1]:
import pandas as pd

df = pd.read_csv("/workspaces/data_5500_code/week_7/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
print("Average age:", df["Age"].mean())

print("Total survivors:", df["Survived"].sum())

print("Unique ports:", df["Embarked"].unique())

Average age: 29.69911764705882
Total survivors: 342
Unique ports: <StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

Sorting DataFrames

In [8]:
expensive_passengers = df.sort_values(by="Fare", ascending=False)
expensive_passengers[["Name", "Fare", "Pclass"]]

                                   Name      Fare  Pclass
679  Cardeza, Mr. Thomas Drake Martinez  512.3292       1
258                    Ward, Miss. Anna  512.3292       1
737              Lesurer, Mr. Gustave J  512.3292       1
88           Fortune, Miss. Mabel Helen  263.0000       1
438                   Fortune, Mr. Mark  263.0000       1
..                                  ...       ...     ...
806              Andrews, Mr. Thomas Jr    0.0000       1
815                    Fry, Mr. Richard    0.0000       1
466               Campbell, Mr. William    0.0000       2
481    Frost, Mr. Anthony Wood "Archie"    0.0000       2
822     Reuchlin, Jonkheer. John George    0.0000       1

[891 rows x 3 columns]

In [12]:
sorted_titanic = df.sort_values(by=["Pclass", "Name"], ascending=[True, True])
sorted_titanic[["Name", "Pclass", "Age"]]

                                                Name  Pclass    Age
730                    Allen, Miss. Elisabeth Walton       1  29.00
305                   Allison, Master. Hudson Trevor       1   0.92
297                     Allison, Miss. Helen Loraine       1   2.00
498  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1  25.00
460                              Anderson, Mr. Harry       1  48.00
..                                               ...     ...    ...
559     de Messemaeker, Mrs. Guillaume Joseph (Emma)       3  36.00
286                          de Mulder, Mr. Theodore       3  30.00
282                        de Pelsmaeker, Mr. Alfons       3  16.00
153                  van Billiard, Mr. Austin Blyler       3  40.50
868                      van Melkebeke, Mr. Philemon       3    NaN

[891 rows x 3 columns]

Trasposing

In [13]:
df.head(1).T

                                   0
PassengerId                        1
Survived                           0
Pclass                             3
Name         Braund, Mr. Owen Harris
Sex                             male
Age                             22.0
SibSp                              1
Parch                              0
Ticket                     A/5 21171
Fare                            7.25
Cabin                            NaN
Embarked                           S